on:
  push:
    tags:
      - "*"

name: Publish Extension
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          yarn: true
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.packageExtension.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            *.vsix